apiVersion: v1
kind: Pod # 2 kinds: pods and jobs
# pods run for 6 hrs, terminate after 6 hrs
# jobs run until you want it to stop/is killed
# usually choose which to run -- for experiments, just use Pod so if u forget to kill pod it will kill itself
metadata:
  name: gxcheng-move-data # define the name of container (prefix-what-do)
  namespace: cyberarch # cyberarch namespace

spec:
  containers:
    - name: data-mover
      image: busybox # docker image
      # imagePullPolicy: Always
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: gxcheng-beat-vol
          mountPath: /gxcheng-beat-vol
        - name: tsc003-beat-vol
          mountPath: /tsc003-beat-vol
  volumes:
    - name: gxcheng-beat-vol
      persistentVolumeClaim:
        claimName: gxcheng-beat-vol
    - name: tsc003-beat-vol
      persistentVolumeClaim:
        claimName: tsc003-beat-vol