apiVersion: v1
kind: Pod # 2 kinds: pods and jobs
# pods run for 6 hrs, terminate after 6 hrs
# jobs run until you want it to stop/is killed
# usually choose which to run -- for experiments, just use Pod so if u forget to kill pod it will kill itself
metadata:
  name: gxcheng-download-files # define the name of container (prefix-what-do)
  namespace: cyberarch # cyberarch namespace

spec:
  containers:
    - name: work-container
      image: tsekai/a2bs_base:latest # docker image
      # imagePullPolicy: Always
      command:
            - bash
            - -c
            - |
              source /usr/local/bin/_activate_current_env.sh
              git clone https://github.com/CatFish47/a2bs.git
              pip install -r a2bs/requirements.txt
              echo "done setup"
              sleep infinity
      resources: #don't sleep infinity on a job unless if u kill it
        requests:
          cpu: "5"
          memory: "10Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "5"
          memory: "10Gi"
          nvidia.com/gpu: "1"
      volumeMounts:
        - name: gxcheng-beat-vol
          mountPath: /gxcheng-beat-vol
  volumes:
    - name: gxcheng-beat-vol
      persistentVolumeClaim:
        claimName: gxcheng-beat-vol
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.product
              operator: In
              values:
                - NVIDIA-GeForce-RTX-4090