apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gxcheng-beat-vol
spec:
  storageClassName: rook-cephfs-east
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi